Allow markdown in caption
florianeckerstorfer/remark-images pull request #8
Opened 2021-03-16 08:53 UTC by amykapernick

Added parsing of caption, to allow for adding markdown in caption, eg. links, bold, italic, etc.

2021-03-16 08:54 UTC, amykapernick commented
Happy to discuss alternative ways to do this, great plugin, and the best that I've been able to find!

2021-03-16 20:36 UTC, florianeckerstorfer commented
Thanks for the contribution, using Markdown in captions was something that I wanted to implement for a while now.

1. At the moment `remark` and `remark-html` are defined as dev dependencies (they are used for the tests), not as dependencies. Before I can merge this PR you would need to add them as dependencies.
2. It would be great if you could add tests for this feature as well.
3. After looking at your PR I was thinking if we should make this configurable. I think we have a few possible options (as in plugin options) here: have an option `enableMarkdownCaptions`, an option to pass an array of remark plugins or instead of including the Markdown processing in this plugin, we provide an option `processCaption`, which is a function `(caption: string) => string`. The user of this plugin could then define their own Remark plugin chain inside a function and pass it to `remark-images`. If the user does not provide a function the caption is not processed.

What do you think? If we would add the `processCaption` option we would not need to add `remark` and `remark-html` as dependencies.

2021-03-16 20:38 UTC, florianeckerstorfer commented
And also thank you for the feedback about this plugin. I appreciate it very much.

2021-03-18 15:34 UTC, florianeckerstorfer requested changes
Awesome, could you update the option name in the README and then this is good to merge.

2021-03-18 15:34 UTC, florianeckerstorfer commented on README.md
> +| `parseCaption`        | `(caption) => caption` | Define a function to process image caption, eg. convert markdown to HTML                  |
I think you forgot to update here with the new name of the option:

```suggestion
| `processOption`        | `(caption) => caption` | Define a function to process image caption, eg. convert markdown to HTML                  |
```

2021-03-20 13:39 UTC, florianeckerstorfer approved these changes

2021-03-20 13:39 UTC, merged

2021-03-20 13:49 UTC, florianeckerstorfer commented
@amykapernick Thanks for the update, I will release a new version ASAP